// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rettit.DAL;

namespace Rettit.DAL.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200420084856_Add-migration Initial")]
    partial class AddmigrationInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rettit.Models.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PostIdId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Posted")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserIdId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PostIdId");

                    b.HasIndex("UserIdId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Rettit.Models.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SubForumIdId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserIdId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubForumIdId");

                    b.HasIndex("UserIdId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Rettit.Models.SubForum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rule1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rule2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rule3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserIdId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserIdId");

                    b.ToTable("SubForum");
                });

            modelBuilder.Entity("Rettit.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Rettit.Models.Comment", b =>
                {
                    b.HasOne("Rettit.Models.Post", "PostId")
                        .WithMany("Comments")
                        .HasForeignKey("PostIdId");

                    b.HasOne("Rettit.Models.User", "UserId")
                        .WithMany("Comments")
                        .HasForeignKey("UserIdId");
                });

            modelBuilder.Entity("Rettit.Models.Post", b =>
                {
                    b.HasOne("Rettit.Models.SubForum", "SubForumId")
                        .WithMany("Posts")
                        .HasForeignKey("SubForumIdId");

                    b.HasOne("Rettit.Models.User", "UserId")
                        .WithMany("Posts")
                        .HasForeignKey("UserIdId");
                });

            modelBuilder.Entity("Rettit.Models.SubForum", b =>
                {
                    b.HasOne("Rettit.Models.User", "UserId")
                        .WithMany("Subforums")
                        .HasForeignKey("UserIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
